logging.file.name: /tmp/logs/sink-users-altice.log
topics:
  - 
    source: source-users-heroku
    sink: sink-users-altice
  - 
    source: source-users-heroku2
    sink: sink-users-altice2
source:
  bootstrap.servers: localhost:29999
sink:
  bootstrap.servers: localhost:29999
