source.bootstrap-servers: localhost:9092
source.group.id: heroku2kafka
source.client.id: heroku2kafka
source.auto.offset.reset: earliest
source.enable.auto.commit: false
source.topic: source-users-heroku
sink.bootstrap-servers: localhost:9092
sink.topic: sink-users-altice
sink.client.id: heroku2kafka
  ## Please use "acks: all" + "idempotence: true" for exactly once delivery when producing to Kafka
sink.acks: all
sink.idempotence: true
